# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-02 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_id', models.IntegerField()),
                ('acct_type', models.CharField(max_length=30)),
                ('balance', models.IntegerField()),
                ('overdraft_history', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('existing_npa', models.DecimalField(decimal_places=3, max_digits=3)),
                ('cash_reserve', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.CharField(max_length=20)),
                ('fam_dependency', models.IntegerField()),
                ('account_no', models.IntegerField()),
                ('income', models.IntegerField()),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('mclr', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
